
site_name: SynapTune
site_url: https://rfc391.github.io/SynapTune
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: lime
repo_url: https://github.com/rfc391/SynapTune
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands: commands.md
  - Architecture: architecture.md
  - API Reference: api.md
